export const FETCHING_TICKETS = 'FETCHING_TICKETS';
export const FETCHING_TICKETS_DONE = 'FETCHING_TICKETS_DONE';
export const FETCHING_TICKETS_ERROR = 'FETCHING_TICKETS_ERROR';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_DONE = 'CREATE_TICKET_DONE';
export const CREATE_TICKET_ERROR = 'CREATE_TICKET_ERROR';

export const SHOW_TOAST = 'SHOW_TOAST'

